[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.1"
ash = "0.35.1"
ash-window = "0.9.0"
rayon = "1.5.1"
cgmath = "0.18.0"
memoffset = "0.6.5"
tobj = "3.2.0"
