[package]
name = "finite-difference"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
renderer = {path = "../renderer"}
rayon = "1.5.1"